name: Android CI

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.jpeg'
      - '**/*.gif'
      - '**/*.svg'
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:
    tags: [ 'v*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-wrapper:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

  build:
    name: Build, Test, Lint
    needs: validate-wrapper
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Print Android SDK/Gradle info
        run: |
          ./gradlew --version | cat
          java -version

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Run lint
        run: ./gradlew lint --stacktrace

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Build release APK (unsigned)
        run: ./gradlew assembleRelease --stacktrace

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk-${{ github.sha }}
          if-no-files-found: warn
          retention-days: 14
          path: |
            app/build/outputs/apk/**/app-*.apk

      - name: Upload lint reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports-${{ github.sha }}
          if-no-files-found: ignore
          retention-days: 7
          path: |
            app/build/reports/lint/*.html
            app/build/reports/lint-results*.xml

      - name: Upload unit test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ github.sha }}
          if-no-files-found: ignore
          retention-days: 7
          path: |
            app/build/test-results/**
            app/build/reports/tests/**

  release-on-tag:
    name: Release on tag
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download APKs
        uses: actions/download-artifact@v4
        with:
          name: apk-${{ github.sha }}
          path: ./dist

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

